apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
      - name: ticket-app
        image: yourdockerhubusername/ticket-app:latest    # Jenkins will replace with specific tag
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"