apiVersion: v1
kind: Service
metadata:
  name: ticket-app-service
spec:
  type: NodePort   # or LoadBalancer in cloud
  selector:
    app: ticket-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080